apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: niloy
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: dreamspace04/nagp-devops-nodejs:16
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          resources:
            requests:
              memory: "250Mi"
              cpu: "250m"
            limits: 
              memory: "400Mi"
              cpu: "500m"   